### ISSUE TITLE
Adapt facilitator screens to the new game flow

### ISSUE THREAD

**Issue by averbraeck** [averbraeck/housinggame-facilitator#7]
The database structure has changed around the allocation of a house. The screen to allocate a house needs to reflect these changes.

Also, more information about the buying / selling of a house needs to be stored in the `playerround` record.

**Comment by vjcortesa** [comment]
These are the quick and dirty screens that we designed today
![231201_Facilitator_House market_allow buying](https://github.com/averbraeck/housinggame-facilitator/assets/8215750/d4a9c6a1-4ef5-4895-9176-b990354ef8f6)
![231201_Facilitator_House market_allow selling](https://github.com/averbraeck/housinggame-facilitator/assets/8215750/b201b874-2dd4-4cbb-872f-b50b37158e81)

**Comment by vjcortesa** [comment]
This is the "ALLOW IMPROVEMENTS" screen
![231208_Facilitator_show houses_allow improvements](https://github.com/averbraeck/housinggame-facilitator/assets/8215750/a212a451-1f7f-4e46-af03-77c094467669)

**Comment by vjcortesa** [comment]
This is the floods screen
Text, next to button:
Roll the dice to calculate the river and rainfall flood damage for this round, and enter the dice roll result

![231208_Facilitator_floods screen](https://github.com/averbraeck/housinggame-facilitator/assets/8215750/35aa9d87-498b-4fca-97a5-587ba8c74c35)

**Comment by vjcortesa** [comment]
![231208_Facilitator_show damage screen](https://github.com/averbraeck/housinggame-facilitator/assets/8215750/2934936a-3c07-4d53-bf1a-0ec69f2ecf9a)

**Comment by vjcortesa** [comment]
![231208_Facilitator_show damage screen](https://github.com/averbraeck/housinggame-facilitator/assets/8215750/2934936a-3c07-4d53-bf1a-0ec69f2ecf9a)

**Comment by averbraeck** [comment]
All screens are present. Further issues are reported as new issues.
